### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SunnyJang38** [sylvanaar/prat-3-0#90] opened 2020-06-05 15:37 UTC
00:34 Interface\AddOns\Prat-3.0-3.8.9\modules\Substitutions.lua:1360: attempt to index local 'v' (a boolean value)
00:34 Interface\AddOns\Prat-3.0-3.8.9\modules\Substitutions.lua:1360: in function `BuildModuleOptions'
Interface\AddOns\Prat-3.0-3.8.9\modules\Substitutions.lua:1349: in function `OnModuleEnable'
Interface\AddOns\Prat-3.0-3.8.9\addon\modules.lua:189: in function <Interface\AddOns\Prat-3.0\addon\modules.lua:178>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:571: in function `EnableAddon'
...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:693: in function <Interface\FrameXML\UIParent.lua:658>

**Comment by sylvanaar** [comment] 2020-06-05 15:44
What's going on with your line numbers. `\Substitutions.lua:1360` 

Line 1360?

**Comment by sylvanaar** [comment] 2020-06-05 16:13
Duplicate of #91

**Closed as completed** 2020-06-05 16:14 UTC
